image: node:latest

stages:
  - build
  - linting
  - test
  - deploy

variables:
  npm_config_cache: "$CI_PROJECT_DIR/.npm"
  CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/cache/Cypress"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm
    - cache/Cypress
    - node_modules

build:
  stage: build
  script:
    - npm ci
    - npm run build --prod
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /skip-ci/
  artifacts:
    paths:
        - dist/


linting:
  stage: linting
  script:
    - npx ng lint
  dependencies:
    - build
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /skip-ci/

test:unit:
  stage: test
  script:
    - npm run test
  dependencies:
    - build
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /skip-ci/

test:e2e:
  stage: test
  image: cypress/base:10
  dependencies:
    - build
  script:
    - npm run e2e
  artifacts:
    paths:
      - cypress/screenshots
      - cypress/videos
    expire_in: 1 day
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /skip-ci/

deploy_prod:
  stage: deploy
  environment:
    name: production
    url: $FIREBASE_URL
  only:
   - master
  dependencies:
    - build
  cache:
    policy: pull
    paths:
      - node_modules/
  script:
    - npm run deploy
  when: manual
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /skip-ci/

